travis: Add static clang build.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -55,10 +55,13 @@ script:
  - ${CXX} --version
  - |
    echo "travis_fold:start:load_script"
-   normal="$(echo -e '\033[0m')" red="$normal$(echo -e '\033[01;31m')" green="$normal$(echo -e '\033[01;32m')"
+   normal="$(echo -e '\033[0m')"
+   red="$normal$(echo -e '\033[01;31m')"
+   green="$normal$(echo -e '\033[01;32m')"
    configureCVC4() {
      echo "CVC4 config - $TRAVIS_CVC4_CONFIG";
-     ./configure.sh --name=build --unit-testing $TRAVIS_CVC4_CONFIG
+     ./contrib/get-symfpu
+     ./configure.sh --unit-testing --symfpu $TRAVIS_CVC4_CONFIG
    }
    error() {
      echo;
@@ -67,41 +70,27 @@ script:
      exit 1;
    }
    makeAutotools() {
+     ./contrib/get-lfsc-checker
      ./autogen.sh
      ./configure debug --with-lfsc --disable-debug-symbols
-     make -j2 check REGRESSION_LEVEL=0 CVC4_REGRESSION_ARGS='--no-early-exit' || error "AUTOTOOLS BUILD/UNIT/SYSTEM/REGRESSION TEST FAILED"
+     make -j2 check REGRESSION_LEVEL=0 CVC4_REGRESSION_ARGS='--no-early-exit' \
+       || error "AUTOTOOLS BUILD/UNIT/SYSTEM/REGRESSION TEST FAILED"
    }
-   #   makeDistcheck() {
-   #     make V=1 -j2 distcheck REGRESSION_LEVEL=0 CVC4_REGRESSION_ARGS='--no-early-exit' ||
-   #       error "DISTCHECK (WITH NEWTHEORY TESTS) FAILED";
-   #   }
    makeCheck() {
      cd build
-     make -j2 check ARGS='-LE regress[1-4]' CVC4_REGRESSION_ARGS='--no-early-exit' || error "BUILD/UNIT/SYSTEM/REGRESSION TEST FAILED"
+     make -j2 check ARGS='-LE regress[1-4]' \
+       CVC4_REGRESSION_ARGS='--no-early-exit' \
+       || error "BUILD/UNIT/SYSTEM/REGRESSION TEST FAILED"
    }
-   makeExamples() {
-     cd build
-     make -j2 examples || error "COULD NOT BUILD EXAMPLES${normal}";
-   }
-   #   addNewTheoryTest() {
-   #       contrib/new-theory test_newtheory || error "NEWTHEORY FAILED";
-   #       grep -q '^THEORIES *=.* test_newtheory' src/Makefile.theories || error "NEWTHEORY FAILED";
-   #       contrib/new-theory --alternate test_newtheory test_newalttheory || error "NEWTHEORY-ALTERNATE FAILED";
-   #       grep -q '^THEORIES *=.* test_newalttheory' src/Makefile.theories || error "NEWTHEORY-ALTERNATE FAILED";
-   #   }
    run() {
      echo "travis_fold:start:$1"
      echo "Running $1"
      $1 || exit 1
      echo "travis_fold:end:$1"
    }
-   [ -n "$TRAVIS_CVC4" ] && [ -n "$TRAVIS_WITH_LFSC" ] && run contrib/get-lfsc-checker
+   [[ "$TRAVIS_CVC4_CONFIG" = *"--lfsc"* ]] && run contrib/get-lfsc-checker
    [ -n "$TRAVIS_AUTOTOOLS" ] && run makeAutotools
-   #   [ -n "$TRAVIS_CVC4" ] && [ -n "$TRAVIS_CVC4_DISTCHECK" ] && run addNewTheoryTest
-   [ -n "$TRAVIS_CVC4" ] && [ -z "$TRAVIS_AUTOTOOLS" ] && run configureCVC4
-   #   [ -n "$TRAVIS_CVC4" ] && [ -n "$TRAVIS_CVC4_DISTCHECK" ] && run makeDistcheck
-   [ -n "$TRAVIS_CVC4" ] && [ -z "$TRAVIS_CVC4_DISTCHECK" ] && [ -z "$TRAVIS_AUTOTOOLS" ] && run makeCheck && run makeExamples
-   [ -z "$TRAVIS_CVC4" ] && error "Unknown Travis-CI configuration"
+   [ -z "$TRAVIS_AUTOTOOLS" ] && run configureCVC4 && run makeCheck
    echo "travis_fold:end:load_script"
  - echo; echo "${green}EVERYTHING SEEMED TO PASS!${normal}"
  - ccache -s
@@ -110,24 +99,19 @@ matrix:
   include:
     # Test with GCC
     - compiler: gcc
-      env:
-        - TRAVIS_CVC4=yes TRAVIS_WITH_LFSC=yes TRAVIS_CVC4_CONFIG='production --language-bindings=java --lfsc'
+      env: TRAVIS_CVC4_CONFIG='production --language-bindings=java,python --lfsc'
     - compiler: gcc
-      env:
-        - TRAVIS_CVC4=yes TRAVIS_WITH_LFSC=yes TRAVIS_CVC4_CONFIG='debug --lfsc --no-debug-symbols'
+      env: TRAVIS_CVC4_CONFIG='debug --lfsc --no-debug-symbols'
 
     # Add autotools build until cmake is the default
     - compiler: gcc
-      env:
-        - TRAVIS_CVC4=yes TRAVIS_WITH_LFSC=yes TRAVIS_AUTOTOOLS=yes
-    #
+      env: TRAVIS_AUTOTOOLS=yes
+
     # Test with Clang
     - compiler: clang
-      env:
-        - TRAVIS_CVC4=yes TRAVIS_WITH_LFSC=yes TRAVIS_CVC4_CONFIG='debug --cln --gpl --no-debug-symbols --no-proofs'
-    - compiler: clang
-      env:
-        - TRAVIS_CVC4=yes TRAVIS_CVC4_DISTCHECK=yes TRAVIS_CVC4_CONFIG='--proofs'
+      env: TRAVIS_CVC4_CONFIG='debug --cln --gpl --no-debug-symbols --no-proofs'
+    - compiler: gcc
+      env: TRAVIS_CVC4_CONFIG='production --static'
 notifications:
   email:
     on_success: change
